**<font size=6>特征工程</font>**

<font size=5>1. 读取数据</font>

In [33]:
import pandas as pd
import numpy as np

这里利用1316A站点2019年1月的数据作为尝试

In [34]:
stationID = "1316A"
datadate = "201901"

In [35]:
filename = "data/"+stationID+"/"+datadate+".csv"
filename

'data/1316A/201901.csv'

In [36]:
data = pd.read_csv(filename, header=0, encoding="utf-8")

<font size=5>2. 查看数据格式及是否有缺失值<font>

In [37]:
#查看前五行数据
data.head()

,date,hour,stationID,AQI,PM2.5,PM2.5_24h,PM10,PM10_24h,SO2,SO2_24h,NO2,NO2_24h,O3,O3_24h,O3_8h,O3_8h_24h,CO,CO_24h
0,20190101,0,1316A,152.0,116.0,85.0,184.0,135.0,21.0,21.0,79.0,65.0,6.0,48.0,13.0,35.0,1.6,1.3
1,20190101,1,1316A,133.0,101.0,87.0,178.0,139.0,21.0,21.0,79.0,66.0,6.0,48.0,6.0,6.0,1.6,1.3
2,20190101,2,1316A,134.0,102.0,88.0,162.0,142.0,23.0,21.0,79.0,67.0,6.0,48.0,6.0,6.0,1.7,1.3
3,20190101,3,1316A,140.0,107.0,90.0,172.0,145.0,21.0,22.0,78.0,67.0,6.0,48.0,6.0,6.0,1.7,1.3
4,20190101,4,1316A,143.0,109.0,92.0,171.0,148.0,19.0,21.0,77.0,67.0,6.0,48.0,6.0,6.0,1.8,1.4

<font color="red">提示：这里PM_2.5_24h表示的是PM2.5在24h内的均值，而PM2.5表示的是实时浓度</font>

In [38]:
#查看数据格式
data.dtypes

date           int64
hour           int64
stationID     object
AQI          float64
PM2.5        float64
PM2.5_24h    float64
PM10         float64
PM10_24h     float64
SO2          float64
SO2_24h      float64
NO2          float64
NO2_24h      float64
O3           float64
O3_24h       float64
O3_8h        float64
O3_8h_24h    float64
CO           float64
CO_24h       float64
dtype: object

In [39]:
#查看数据形状
data.shape

(744, 18)

In [40]:
#查看是否有缺失值
data.count()

date         744
hour         744
stationID    744
AQI          709
PM2.5        706
PM2.5_24h    740
PM10         702
PM10_24h     740
SO2          738
SO2_24h      743
NO2          733
NO2_24h      743
O3           735
O3_24h       743
O3_8h        743
O3_8h_24h    743
CO           737
CO_24h       743
dtype: int64

这里可以看到还是有缺失值存在的
**<font color=red>在将数据应用于系统之前，一定要对缺省值进行处理</font>**

In [41]:
#找出含有缺失值的列
hasNAN = data.isnull().any()
hasNAN[hasNAN==True]

AQI          True
PM2.5        True
PM2.5_24h    True
PM10         True
PM10_24h     True
SO2          True
SO2_24h      True
NO2          True
NO2_24h      True
O3           True
O3_24h       True
O3_8h        True
O3_8h_24h    True
CO           True
CO_24h       True
dtype: bool

<font size=5>3. 处理缺失值</font>

我的想法是：先找出含NAN值的列，然后分别计算这些列的均值，然后进行填充

In [42]:
#nancolslist存放含NAN值的列名信息
nancolslist = list(hasNAN[hasNAN==True].index)
len(nancolslist)

15

这里用round(数据，小数点位数)使得均值精确到小数点后两位

In [43]:
#计算每一项指标的均值
for indicator in nancolslist:
    print(round(data[indicator].mean(),2))

163.04
121.8
123.16
180.52
181.14
17.9
18.04
66.65
67.22
22.65
53.0
22.09
25.97
1.43
1.43

In [44]:
#利用均值填充缺失值
for indicator in nancolslist:
    colsmean = round(data[indicator].mean(),2)
    data[indicator] = data[indicator].fillna(colsmean)

In [45]:

#查看填充后的数据
data[50:100]

,date,hour,stationID,AQI,PM2.5,PM2.5_24h,PM10,PM10_24h,SO2,SO2_24h,NO2,NO2_24h,O3,O3_24h,O3_8h,O3_8h_24h,CO,CO_24h
50,20190103,2,1316A,159.00,121.0,140.0,182.00,205.0,22.0,20.0,86.00,77.0,13.00,94.0,16.0,20.0,1.50,1.6
51,20190103,3,1316A,159.00,121.0,138.0,174.00,203.0,19.0,20.0,84.00,76.0,14.00,94.0,16.0,20.0,1.40,1.6
52,20190103,4,1316A,165.00,125.0,136.0,176.00,201.0,18.0,20.0,89.00,76.0,8.00,94.0,14.0,20.0,1.50,1.6
53,20190103,5,1316A,166.00,126.0,133.0,189.00,199.0,17.0,20.0,87.00,76.0,7.00,94.0,12.0,20.0,1.50,1.6
54,20190103,6,1316A,163.00,124.0,131.0,178.00,196.0,16.0,20.0,85.00,75.0,6.00,94.0,11.0,20.0,1.50,1.6
55,20190103,7,1316A,168.00,127.0,129.0,181.00,193.0,17.0,20.0,82.00,75.0,6.00,94.0,11.0,20.0,1.60,1.6
56,20190103,8,1316A,176.00,133.0,127.0,188.00,190.0,19.0,20.0,84.00,74.0,6.00,94.0,10.0,20.0,1.80,1.5
57,20190103,9,1316A,188.00,141.0,125.0,215.00,188.0,24.0,20.0,82.00,74.0,9.00,94.0,9.0,20.0,1.80,1.5
58,20190103,10,1316A,198.00,148.0,124.0,228.00,186.0,21.0,20.0,80.00,74.0,10.00,94.0,8.0,20.0,1.90,1.5
59,20190103,11,1316A,203.00,153.0,124.0,224.00,186.0,20.0,20.0,83.00,74.0,13.00,94.0,8.0,20.0,2.00,1.5
60,20190103,12,1316A,203.00,153.0,125.0,241.00,186.0,18.0,20.0,92.00,75.0,14.00,94.0,9.0,20.0,2.00,1.6
61,20190103,13,1316A,200.00,150.0,126.0,235.00,188.0,16.0,20.0,100.00,78.0,19.00,94.0,10.0,20.0,1.90,1.6
62,20190103,14,1316A,198.00,148.0,127.0,217.00,190.0,16.0,21.0,83.00,80.0,30.00,94.0,13.0,20.0,1.43,1.6
63,20190103,15,1316A,133.00,121.8,128.0,216.00,192.0,18.0,20.0,70.00,81.0,38.00,81.0,17.0,20.0,1.30,1.6
64,20190103,16,1316A,189.00,142.0,128.0,204.00,193.0,15.0,20.0,54.00,81.0,57.00,67.0,24.0,24.0,1.20,1.6
65,20190103,17,1316A,189.00,142.0,129.0,178.00,192.0,15.0,19.0,54.00,81.0,60.00,64.0,30.0,30.0,1.20,1.6
66,20190103,18,1316A,211.00,161.0,131.0,194.00,193.0,20.0,19.0,72.00,81.0,44.00,60.0,34.0,34.0,1.40,1.6
67,20190103,19,1316A,237.00,187.0,134.0,227.00,195.0,30.0,20.0,90.00,82.0,28.00,60.0,36.0,36.0,1.70,1.6
68,20190103,20,1316A,240.00,190.0,137.0,239.00,198.0,29.0,20.0,96.00,82.0,21.00,60.0,37.0,37.0,1.40,1.6
69,20190103,21,1316A,225.00,175.0,140.0,229.00,200.0,20.0,20.0,92.00,82.0,23.00,60.0,38.0,38.0,1.10,1.5
70,20190103,22,1316A,218.00,168.0,143.0,220.00,203.0,15.0,20.0,75.00,82.0,31.00,60.0,38.0,38.0,1.00,1.5
71,20190103,23,1316A,222.00,172.0,145.0,199.00,204.0,12.0,19.0,74.00,81.0,25.00,60.0,36.0,38.0,0.90,1.5
72,20190104,0,1316A,234.00,184.0,148.0,208.00,205.0,9.0,19.0,92.00,82.0,8.00,60.0,30.0,38.0,1.20,1.5
73,20190104,1,1316A,248.00,198.0,152.0,212.00,206.0,8.0,18.0,92.00,82.0,5.00,60.0,5.0,5.0,1.20,1.5
74,20190104,2,1316A,250.00,200.0,155.0,209.00,208.0,8.0,18.0,87.00,82.0,6.00,60.0,6.0,6.0,1.20,1.5
75,20190104,3,1316A,254.00,204.0,159.0,215.00,209.0,8.0,17.0,79.00,82.0,10.00,60.0,7.0,7.0,1.30,1.5
76,20190104,4,1316A,259.00,209.0,162.0,210.00,211.0,8.0,17.0,68.00,81.0,14.00,60.0,9.0,9.0,0.90,1.4
77,20190104,5,1316A,255.00,205.0,166.0,211.00,212.0,8.0,16.0,60.00,80.0,20.00,60.0,11.0,11.0,0.90,1.4
78,20190104,6,1316A,253.00,203.0,169.0,205.00,213.0,7.0,16.0,49.00,79.0,30.00,60.0,14.0,14.0,0.70,1.4
79,20190104,7,1316A,256.00,206.0,173.0,221.00,214.0,7.0,15.0,48.00,77.0,30.00,60.0,16.0,16.0,0.70,1.3
80,20190104,8,1316A,245.00,195.0,175.0,215.00,216.0,8.0,15.0,48.00,76.0,32.00,60.0,18.0,18.0,0.70,1.3
81,20190104,9,1316A,283.00,233.0,179.0,241.00,217.0,7.0,14.0,72.00,75.0,7.00,60.0,19.0,19.0,1.10,1.3
82,20190104,10,1316A,368.00,318.0,187.0,180.52,216.0,24.0,14.0,95.00,76.0,9.00,60.0,19.0,19.0,2.00,1.3
83,20190104,11,1316A,395.00,345.0,195.0,376.00,223.0,33.0,15.0,103.00,77.0,11.00,60.0,19.0,19.0,2.60,1.3
84,20190104,12,1316A,395.00,345.0,203.0,402.00,230.0,38.0,16.0,103.00,77.0,15.00,60.0,19.0,19.0,2.70,1.3
85,20190104,13,1316A,395.00,345.0,212.0,390.00,236.0,39.0,17.0,103.00,77.0,17.00,60.0,19.0,19.0,2.80,1.4
86,20190104,14,1316A,395.00,345.0,221.0,386.00,244.0,38.0,18.0,99.00,78.0,23.00,60.0,18.0,19.0,3.00,1.4
87,20190104,15,1316A,395.00,345.0,226.0,377.00,251.0,36.0,18.0,95.00,79.0,27.00,60.0,18.0,19.0,2.90,1.5
88,20190104,16,1316A,395.00,345.0,234.0,363.00,258.0,35.0,19.0,97.00,81.0,26.00,60.0,17.0,19.0,2.90,1.6
89,20190104,17,1316A,395.00,345.0,243.0,353.00,265.0,38.0,20.0,104.00,83.0,19.00,44.0,18.0,19.0,2.90,1.6
90,20190104,18,1316A,395.00,345.0,250.0,348.00,272.0,38.0,21.0,112.00,85.0,13.00,32.0,19.0,19.0,2.90,1.7
91,20190104,19,1316A,206.00,121.8,253.0,354.00,278.0,38.0,21.0,112.00,86.0,22.65,32.0,20.0,20.0,3.00,1.7
92,20190104,20,1316A,361.00,311.0,258.0,346.00,282.0,40.0,22.0,66.65,85.0,22.65,32.0,21.0,21.0,3.10,1.8
93,20190104,21,1316A,352.00,302.0,264.0,373.00,288.0,17.9,22.0,66.65,85.0,8.00,32.0,19.0,21.0,3.10,1.9
94,20190104,22,1316A,344.00,294.0,269.0,364.00,295.0,17.9,22.0,109.00,86.0,8.00,32.0,17.0,21.0,1.43,1.9
95,20190104,23,1316A,163.04,121.8,274.0,180.52,299.0,45.0,24.0,111.00,88.0,8.00,32.0,14.0,21.0,3.20,2.0
96,20190105,0,1316A,163.04,121.8,278.0,180.52,303.0,43.0,25.0,115.00,89.0,7.00,32.0,10.0,21.0,3.10,2.1
97,20190105,1,1316A,360.00,310.0,283.0,382.00,311.0,41.0,27.0,114.00,90.0,7.00,32.0,7.0,7.0,3.00,2.2
98,20190105,2,1316A,368.00,318.0,289.0,381.00,320.0,40.0,28.0,117.00,92.0,6.00,32.0,6.0,7.0,3.10,2.3
99,20190105,3,1316A,341.00,291.0,293.0,383.00,328.0,42.0,30.0,115.00,93.0,6.00,32.0,6.0,7.0,3.10,2.4

这样就填充好缺失值了，可以进行下一步操作。

<font size=5>4. 日期处理</font>

毕竟是时间序列，肯定要对时间进行处理。

In [46]:
#查看datetime类型
type(data.date)

pandas.core.series.Series

In [47]:
#将数据转化为datetime类型
data["date"]= pd.to_datetime(data["date"], format='%Y%m%d')

In [48]:
data.shape

(744, 18)

发现当前数据集中有18个属性，其中date已经被我们修改为datetime类型的了

In [49]:
#查看更改为datetime类型的date数据
data.head()

,date,hour,stationID,AQI,PM2.5,PM2.5_24h,PM10,PM10_24h,SO2,SO2_24h,NO2,NO2_24h,O3,O3_24h,O3_8h,O3_8h_24h,CO,CO_24h
0,2019-01-01,0,1316A,152.0,116.0,85.0,184.0,135.0,21.0,21.0,79.0,65.0,6.0,48.0,13.0,35.0,1.6,1.3
1,2019-01-01,1,1316A,133.0,101.0,87.0,178.0,139.0,21.0,21.0,79.0,66.0,6.0,48.0,6.0,6.0,1.6,1.3
2,2019-01-01,2,1316A,134.0,102.0,88.0,162.0,142.0,23.0,21.0,79.0,67.0,6.0,48.0,6.0,6.0,1.7,1.3
3,2019-01-01,3,1316A,140.0,107.0,90.0,172.0,145.0,21.0,22.0,78.0,67.0,6.0,48.0,6.0,6.0,1.7,1.3
4,2019-01-01,4,1316A,143.0,109.0,92.0,171.0,148.0,19.0,21.0,77.0,67.0,6.0,48.0,6.0,6.0,1.8,1.4

In [50]:
#查看下类型
data.dtypes

date         datetime64[ns]
hour                  int64
stationID            object
AQI                 float64
PM2.5               float64
PM2.5_24h           float64
PM10                float64
PM10_24h            float64
SO2                 float64
SO2_24h             float64
NO2                 float64
NO2_24h             float64
O3                  float64
O3_24h              float64
O3_8h               float64
O3_8h_24h           float64
CO                  float64
CO_24h              float64
dtype: object

在这里发现date真的转换位datetime类型

目前的datetime中年月日信息是连在一起的，便于后续操作，我们把信息独立分成三列

In [51]:
data["year"] = pd.DatetimeIndex(data.date).year
data["month"] = pd.DatetimeIndex(data.date).month
data["day"] = pd.DatetimeIndex(data.date).day

考虑到周末和工作日人们的生活方式可能与平常不大相同，单独再增加一列dayOfWeek，表示当前是一周的第几天

In [52]:
data["dayOfWeek"] = pd.DatetimeIndex(data.date).dayofweek

**<font color=red size=3>注意：dayOfWeek开始值是0，而不是我们想象中的周一，结束值是6，代表周日</font>**

In [53]:
#再看下当前数据
data.head()

,date,hour,stationID,AQI,PM2.5,PM2.5_24h,PM10,PM10_24h,SO2,SO2_24h,...,O3,O3_24h,O3_8h,O3_8h_24h,CO,CO_24h,year,month,day,dayOfWeek
0,2019-01-01,0,1316A,152.0,116.0,85.0,184.0,135.0,21.0,21.0,...,6.0,48.0,13.0,35.0,1.6,1.3,2019,1,1,1
1,2019-01-01,1,1316A,133.0,101.0,87.0,178.0,139.0,21.0,21.0,...,6.0,48.0,6.0,6.0,1.6,1.3,2019,1,1,1
2,2019-01-01,2,1316A,134.0,102.0,88.0,162.0,142.0,23.0,21.0,...,6.0,48.0,6.0,6.0,1.7,1.3,2019,1,1,1
3,2019-01-01,3,1316A,140.0,107.0,90.0,172.0,145.0,21.0,22.0,...,6.0,48.0,6.0,6.0,1.7,1.3,2019,1,1,1
4,2019-01-01,4,1316A,143.0,109.0,92.0,171.0,148.0,19.0,21.0,...,6.0,48.0,6.0,6.0,1.8,1.4,2019,1,1,1

In [54]:
#查看更新后的data的shape：
data.shape

(744, 22)

这里可以看到，由之前的18列扩展为22列。因为我们新增了四列：year,month,day,dayOfWeek

其实，此时的date、stationID数据就不是很有用了，我们可以先将这列去掉，<font color=red>不过保险起见，我们先保存一下吧</font>

In [55]:
initialData = data

In [56]:
#扔掉date、stationID字段
data = data.drop(["date", "stationID"], axis=1)

In [57]:
#查看data的shape:
data.shape

(744, 20)

可以发现由于我们删掉了两列，此时的数据从22列变为20列

In [58]:
#重新查看数据
data.head()

,hour,AQI,PM2.5,PM2.5_24h,PM10,PM10_24h,SO2,SO2_24h,NO2,NO2_24h,O3,O3_24h,O3_8h,O3_8h_24h,CO,CO_24h,year,month,day,dayOfWeek
0,0,152.0,116.0,85.0,184.0,135.0,21.0,21.0,79.0,65.0,6.0,48.0,13.0,35.0,1.6,1.3,2019,1,1,1
1,1,133.0,101.0,87.0,178.0,139.0,21.0,21.0,79.0,66.0,6.0,48.0,6.0,6.0,1.6,1.3,2019,1,1,1
2,2,134.0,102.0,88.0,162.0,142.0,23.0,21.0,79.0,67.0,6.0,48.0,6.0,6.0,1.7,1.3,2019,1,1,1
3,3,140.0,107.0,90.0,172.0,145.0,21.0,22.0,78.0,67.0,6.0,48.0,6.0,6.0,1.7,1.3,2019,1,1,1
4,4,143.0,109.0,92.0,171.0,148.0,19.0,21.0,77.0,67.0,6.0,48.0,6.0,6.0,1.8,1.4,2019,1,1,1

这样数据好很多了，就是位置需要再调整一下

In [75]:
orderlist = ["year", "month", "day", "hour", "AQI", "PM2.5", "PM2.5_24h", "PM10", "PM10_24h","SO2","SO2_24h","NO2","NO2_24h","O3", "O3_24h", "O3_8h", "O3_8h_24h", "CO", "CO_24h", "dayOfWeek"]
data = data[orderlist]
data.head()

,year,month,day,hour,AQI,PM2.5,PM2.5_24h,PM10,PM10_24h,SO2,SO2_24h,NO2,NO2_24h,O3,O3_24h,O3_8h,O3_8h_24h,CO,CO_24h,dayOfWeek
0,2019,1,1,0,152.0,116.0,85.0,184.0,135.0,21.0,21.0,79.0,65.0,6.0,48.0,13.0,35.0,1.6,1.3,1
1,2019,1,1,1,133.0,101.0,87.0,178.0,139.0,21.0,21.0,79.0,66.0,6.0,48.0,6.0,6.0,1.6,1.3,1
2,2019,1,1,2,134.0,102.0,88.0,162.0,142.0,23.0,21.0,79.0,67.0,6.0,48.0,6.0,6.0,1.7,1.3,1
3,2019,1,1,3,140.0,107.0,90.0,172.0,145.0,21.0,22.0,78.0,67.0,6.0,48.0,6.0,6.0,1.7,1.3,1
4,2019,1,1,4,143.0,109.0,92.0,171.0,148.0,19.0,21.0,77.0,67.0,6.0,48.0,6.0,6.0,1.8,1.4,1

<font color="red">这里的数据为啥又称科学计数了，我们前面处理过的保留小数点后两位，这是个神马情况！</font>

In [81]:
data.values

array([[2019. ,    1. ,    1. , ...,    1.6,    1.3,    1. ],
       [2019. ,    1. ,    1. , ...,    1.6,    1.3,    1. ],
       [2019. ,    1. ,    1. , ...,    1.7,    1.3,    1. ],
       ...,
       [2019. ,    1. ,   31. , ...,    1.1,    1.1,    3. ],
       [2019. ,    1. ,   31. , ...,    1. ,    1.1,    3. ],
       [2019. ,    1. ,   31. , ...,    1. ,    1.1,    3. ]])

为了不使用科学记数法，这里我们设置一下

In [82]:
np.set_printoptions(precision=2, suppress=True, threshold=2)

In [83]:
data.values

array([[2019. ,    1. ,    1. , ...,    1.6,    1.3,    1. ],
       [2019. ,    1. ,    1. , ...,    1.6,    1.3,    1. ],
       [2019. ,    1. ,    1. , ...,    1.7,    1.3,    1. ],
       ...,
       [2019. ,    1. ,   31. , ...,    1.1,    1.1,    3. ],
       [2019. ,    1. ,   31. , ...,    1. ,    1.1,    3. ],
       [2019. ,    1. ,   31. , ...,    1. ,    1.1,    3. ]])

可以看到，数据整洁了很多

In [65]:
#再查看下数据类型
data.dtypes

year           int64
month          int64
day            int64
hour           int64
AQI          float64
PM2.5        float64
PM2.5_24h    float64
PM10         float64
PM10_24h     float64
SO2          float64
SO2_24h      float64
NO2          float64
NO2_24h      float64
O3           float64
O3_24h       float64
O3_8h        float64
O3_8h_24h    float64
CO           float64
CO_24h       float64
dayOfWeek      int64
dtype: object

<font size=5>5. 将DataFrame格式的数据转化为ndarray类型</font>

将所有列名保存在all_featurenames列表中

In [85]:
all_featurenames = list(data.columns)

In [86]:
all_featurenames

['year',
 'month',
 'day',
 'hour',
 'AQI',
 'PM2.5',
 'PM2.5_24h',
 'PM10',
 'PM10_24h',
 'SO2',
 'SO2_24h',
 'NO2',
 'NO2_24h',
 'O3',
 'O3_24h',
 'O3_8h',
 'O3_8h_24h',
 'CO',
 'CO_24h',
 'dayOfWeek']

In [87]:
data_array = data.values

In [88]:
data_array.shape

(744, 20)

<font color="red">选择目标值为AQI指数，空气质量指数（也就是手机里面经常看到的）</font>

In [89]:
data_target = data["AQI"].values

In [90]:
data_target.shape

(744,)

<font color="red">剩下的数据作为特征数据</font>

In [91]:
residue_features = data.drop(["AQI"], axis=1)
residue_featurenames = list(residue_features.columns)

In [92]:
residue_featurenames

['year',
 'month',
 'day',
 'hour',
 'PM2.5',
 'PM2.5_24h',
 'PM10',
 'PM10_24h',
 'SO2',
 'SO2_24h',
 'NO2',
 'NO2_24h',
 'O3',
 'O3_24h',
 'O3_8h',
 'O3_8h_24h',
 'CO',
 'CO_24h',
 'dayOfWeek']

In [93]:
data_features = residue_features.values
data_features.shape

(744, 19)

**<font size=6>绘制热力图（相关系数矩阵图）</font>**

In [94]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

<font size=5>1. 首先对数据进行标准化处理</font>

In [95]:
scaler = StandardScaler().fit(data_array)
data_feature_scaled = np.round(scaler.transform(data_array),2)

利用np.round(data,num)将数据精确到小数点后num位。

In [96]:
data_feature_scaled[:5,:]

array([[ 0.  ,  0.  , -1.68, ...,  0.28, -0.29, -0.98],
       [ 0.  ,  0.  , -1.68, ...,  0.28, -0.29, -0.98],
       [ 0.  ,  0.  , -1.68, ...,  0.44, -0.29, -0.98],
       [ 0.  ,  0.  , -1.68, ...,  0.44, -0.29, -0.98],
       [ 0.  ,  0.  , -1.68, ...,  0.6 , -0.08, -0.98]])

<font size=5>2.计算相关系数矩阵</font>

numpy中用cov函数得到，pandas中的corr()也可以得到相同的结果<br>
numpy.cov(m, y=None, rowvar=True, bias=False, ddof=None, fweights=None, aweights=None)<br>
m: numpy矩阵<br>
y: 可有可无<br>
rowvar: 一个布尔值，描述矩阵的信息。默认情况下，m矩阵的每一行对应一个特征，每一列对应一个样本。如果是每一列对应一个特征的话，将其置为False即可。
bias: 计算协方差时，如果bias=True，分母为样本数，表示有偏估计。默认情况下为False，表示无偏估计，此时分母为样本数-1。
ddof: 自由度

In [97]:
featureCov = np.cov(data_feature_scaled, rowvar=False)

In [98]:
%matplotlib

Using matplotlib backend: Qt5Agg

<font size=5>3. 绘制热力图，便于查看特征之间的相关性</font>

sns.heatmap()用于绘制热力图<br>
参数：<br>
annot=True:显示热力图上的数值大小<br>
square=True:将图变成一个正方形，默认时一个矩形<br>
cmap：配色方案<br>

In [99]:
fig = plt.figure("Correlation Figure")
plt.subplots(figsize=(12,12))
sns.heatmap(featureCov, annot=True, square=True, cmap="Blues", fmt=".2f", 
            xticklabels=all_featurenames, yticklabels=all_featurenames)
plt.title("Correlation heatmap")

Text(0.5,1,'Correlation heatmap')

在这里我们可以发现与AQI相关的特征，将这些特征用于模型的训练

**<font size=6> 基于随机森林模型来选择特征</font>**

In [ ]:
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

<font size=4>1. 划分数据集</font>

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data_features, data_target, random_state=42, test_size=0.3)

<font size=4>2. 构建选择特征的模型</font>

In [ ]:
select = SelectFromModel(RandomForestRegressor(n_estimators=100, random_state=42), threshold="median")

In [ ]:
select.fit(X_train, y_train)

In [ ]:
X_train_selected = select.transform(X_train)
X_train_selected.shape

发现选择了10个特征，查看这10个特征，可以利用get_support()方法查看所选择的属性，其中为True的是选择的值

In [ ]:
mask = select.get_support()
mask

In [ ]:
np.array(residue_featurenames)[mask == True]

可以发现选择的和AQI高度相关的10个特征是：PM2.5, PM2.5_24h，PM10，PM10_24h, SO2, NO2, NO2_24h, 03_24h, CO, CO_24h